"""Remediation patches for a resource assessment.

Patches are proposals for a human to review and apply; nothing is executed.
"""
from __future__ import annotations

import difflib
import json
import re
from pathlib import Path

from ..analysis.traffic import Policy
from ..collectors.dns_zone import DnsRecord
from ..knowledge.providers import ACCOUNT_REGIONAL_NAME, AZURE_WEBAPP_TYPES, EB_TYPES, S3_TYPES
from ..models import Patch, PathAssessment, Reference, RefKind, RetiringResource, Verdict


def _hcl_label(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_") or "retained"


def route53_delete_batch(records: list[DnsRecord], comment: str) -> Patch | None:
    changes = []
    for r in records:
        rs = {k: v for k, v in r.raw.items() if k in ("Name", "Type", "TTL", "ResourceRecords", "AliasTarget",
                                                       "SetIdentifier", "Weight", "Region", "Failover")}
        if rs:
            changes.append({"Action": "DELETE", "ResourceRecordSet": rs})
    if not changes:
        return None
    body = json.dumps({"Comment": comment, "Changes": changes}, indent=2)
    return Patch("route53_change_batch", "Delete the surviving DNS records (Route 53 change batch)",
                 body + "\n\n# apply with:\n# aws route53 change-resource-record-sets "
                 "--hosted-zone-id <ZONE_ID> --change-batch file://change-batch.json",
                 [r.location for r in records])


def zone_file_advice(records: list[DnsRecord]) -> Patch | None:
    if not records:
        return None
    lines = [f"{r.name}.  {r.ttl or ''}  IN  {r.type}  {' '.join(r.values)}" for r in records]
    return Patch("advice", "Remove these records from the zone file",
                 "Delete (or repoint to a resource you keep) the following records, then bump the SOA serial:\n"
                 + "\n".join(lines), [r.location for r in records])


def code_patch(repo_root: Path, refs: list[Reference], old: str, new: str) -> Patch | None:
    files = sorted({r.location.rsplit(":", 1)[0] for r in refs})
    diffs = []
    for rel in files:
        p = repo_root / rel
        try:
            before = p.read_text()
        except OSError:
            continue
        after = re.sub(rf"(?<![a-z0-9.-]){re.escape(old)}(?![a-z0-9-])", new, before)
        if after != before:
            diffs.append("".join(difflib.unified_diff(before.splitlines(True), after.splitlines(True),
                                                      f"a/{rel}", f"b/{rel}")))
    if not diffs:
        return None
    return Patch("code_diff", f"Rewrite references from {old} to {new}", "".join(diffs), files)


def tombstone(res: RetiringResource, policy: Policy, chosen: str | None = None) -> Patch:
    if res.type in S3_TYPES:
        label = _hcl_label(res.address.split(".")[-1])
        acct = policy.org_account_ids[0] if policy.org_account_ids else "<ACCOUNT_ID>"
        region = res.region or "<REGION>"
        prefix = re.sub(r"[^a-z0-9-]", "-", (res.name or "bucket").lower())[:40].strip("-")
        new_name = chosen or f"{prefix}-{acct}-{region}-an"
        body = f'''# Keep owning the bucket name instead of releasing it.
# 1. empty the bucket (objects and versions), 2. remove website/CORS configuration,
# 3. keep the resource below in your configuration.
resource "aws_s3_bucket" "{label}" {{
  bucket = "{res.name}"
  lifecycle {{
    prevent_destroy = true
  }}
}}

resource "aws_s3_bucket_public_access_block" "{label}" {{
  bucket                  = aws_s3_bucket.{label}.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

# If the content must move, create its replacement in your account regional namespace,
# which other accounts cannot claim (format verified from the AWS SDK model):
#   bucket           = "{new_name}"
#   bucket_namespace = "account-regional"
'''
        if ACCOUNT_REGIONAL_NAME.match(new_name) is None:
            body += "#   (fill in ACCOUNT_ID and REGION to obtain a valid account-regional name)\n"
        return Patch("terraform_hcl", f"Tombstone {res.address}: keep the name, drop the content", body, [res.address])
    if res.type in AZURE_WEBAPP_TYPES:
        return Patch("advice", f"Tombstone {res.address}",
                     f"Keep the app name {res.name!r} allocated (stop the app or move it to a free plan) instead "
                     "of deleting it. Create replacements with autoGeneratedDomainNameLabelScope set (for example "
                     "NoReuse) so their default hostnames cannot be re-used by another tenant.", [res.address])
    if res.type in EB_TYPES:
        return Patch("advice", f"Tombstone {res.address}",
                     f"The CNAME prefix {res.name!r} returns to the shared pool when the environment is terminated. "
                     "Keep a minimal environment holding the prefix until every reference is gone, or remove the "
                     "references first.", [res.address])
    return Patch("advice", f"Retain {res.address}", "Keep the resource name allocated.", [res.address])


def owner_check_advice(refs: list[Reference], policy: Policy) -> Patch | None:
    sdk = [r for r in refs if r.kind == RefKind.CODE and r.integrity_control is None and "Bucket" in r.text]
    if not sdk:
        return None
    acct = policy.org_account_ids[0] if policy.org_account_ids else "<ACCOUNT_ID>"
    return Patch("advice", "Add an owner check to S3 API calls",
                 f"Pass ExpectedBucketOwner='{acct}' on these S3 API calls; S3 then refuses a bucket owned by any "
                 "other account (HTTP 403):\n" + "\n".join(f"  {r.location}: {r.text}" for r in sdk),
                 [r.location for r in sdk])


def build(res: RetiringResource, verdict: Verdict, refs: list[Reference], paths: list[PathAssessment],
          dns_by_ref: dict[str, DnsRecord], repo_roots: dict[str, Path], policy: Policy,
          migrate_to: dict[str, str]) -> list[Patch]:
    if verdict in (Verdict.RELEASE, Verdict.NOT_NAME_BEARING):
        return []
    live = {p.reference_id for p in paths if p.status != "safe"}
    patches: list[Patch] = []
    dns_live = [dns_by_ref[r.id] for r in refs if r.id in live and r.id in dns_by_ref]
    r53 = [d for d in dns_live if d.raw]
    bind = [d for d in dns_live if not d.raw]
    for p in (route53_delete_batch(r53, f"RetireSafe: remove references to {res.name}"), zone_file_advice(bind)):
        if p:
            patches.append(p)
    code = [r for r in refs if r.kind == RefKind.CODE and r.id in live]
    new = migrate_to.get(res.name or "")
    if new and code:
        by_repo: dict[str, list[Reference]] = {}
        for r in code:
            by_repo.setdefault(r.location.split("::", 1)[0], []).append(r)
        for repo, rs in by_repo.items():
            local = [Reference(**{**r.__dict__, "location": r.location.split("::", 1)[1]}) for r in rs]
            targets = {r.target_name for r in rs}
            for old in sorted(targets, key=len, reverse=True):
                p = code_patch(repo_roots[repo], [x for x in local if x.target_name == old], old,
                               new if old == res.name else old.replace(res.name or "", new))
                if p:
                    patches.append(p)
    elif code:
        patches.append(Patch("advice", "Update or remove code references",
                             "\n".join(f"  {r.location}: {r.text}" for r in code), [r.location for r in code]))
    adv = owner_check_advice([r for r in refs if r.id in live], policy)
    if adv:
        patches.append(adv)
    iac = [r for r in refs if r.kind == RefKind.IAC and r.id in live]
    if iac:
        patches.append(Patch("advice", "Update infrastructure that still references the resource",
                             "\n".join(f"  {r.location}: {r.text}" for r in iac), [r.location for r in iac]))
    if verdict in (Verdict.TOMBSTONE, Verdict.BLOCK, Verdict.REVIEW):
        patches.append(tombstone(res, policy, new))
    return patches
