"""Source register for every rule the engine applies.

Each rule in ``providers.py`` cites one or more of these ids. "verified_via"
records how the fact was cross-checked when the knowledge base was built
(2026-10-01).
"""

SOURCES = {
    "aws-sdk-s3-createbucket": {
        "title": "AWS SDK service model, S3 CreateBucket / BucketNamespace (botocore s3 2006-03-01 service-2.json)",
        "quote": ("General purpose buckets exist in a global namespace, which means that each bucket name must "
                  "be unique across all Amazon Web Services accounts in all the Amazon Web Services Regions "
                  "within a partition."),
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "aws-sdk-s3-account-regional": {
        "title": "AWS SDK service model, S3 CreateBucket BucketNamespace member (x-amz-bucket-namespace)",
        "quote": ("Your account regional namespace is a subdivision of the global namespace that only your account "
                  "can create buckets in. ... Bucket names must follow the format "
                  "bucket-name-prefix-accountId-region-an (for example, amzn-s3-demo-bucket-111122223333-us-west-2-an)."),
        "verified_via": "botocore data model shipped with boto3 1.43.106; enum values account-regional | global",
    },
    "aws-sdk-s3-expected-owner": {
        "title": "AWS SDK service model, ExpectedBucketOwner (x-amz-expected-bucket-owner)",
        "quote": ("If the account ID that you provide does not match the actual owner of the bucket, the request "
                  "fails with the HTTP status code 403 Forbidden (access denied)."),
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "tf-aws-provider-schema": {
        "title": "Terraform AWS provider 6.67.0 schema: aws_s3_bucket.bucket_namespace, website_endpoint",
        "quote": "aws_s3_bucket attributes include bucket, bucket_prefix, bucket_namespace, website_endpoint",
        "verified_via": "terraform providers schema -json (Terraform 1.16.4, provider SHA256 verified)",
    },
    "aws-sdk-eb-checkdns": {
        "title": "AWS SDK service model, Elastic Beanstalk CheckDNSAvailability",
        "quote": "Checks if the specified CNAME is available. / CNAMEPrefix: The prefix used when this CNAME is reserved.",
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "azure-sdk-web-label-scope": {
        "title": "Azure SDK azure-mgmt-web 11.0.1, autoGeneratedDomainNameLabelScope",
        "quote": ("Indicates the endpoint name reuse scope. The default value is TenantReuse. Supported values are "
                  "TenantReuse, SubscriptionReuse, ResourceGroupReuse, NoReuse."),
        "verified_via": "azure-mgmt-web 11.0.1 model docstrings",
    },
    "ms-learn-dangling-dns": {
        "title": "Microsoft Learn: Prevent dangling DNS entries and avoid subdomain takeover",
        "url": "https://learn.microsoft.com/en-us/azure/security/fundamentals/subdomain-takeover",
        "verified_via": "cited in the research brief [1]; site not reachable from the build sandbox",
    },
    "infoblox-cdc-2025": {
        "title": "Infoblox 2025: CDC abandoned Azure endpoint takeover",
        "url": "https://www.infoblox.com/blog/threat-intelligence/how-scammers-hijack-major-brands/",
        "verified_via": "research brief [2]",
    },
    "infoblox-hazyhawk-2025": {
        "title": "Infoblox 2025: Hazy Hawk (incl. hijacked oercommons S3 bucket)",
        "url": ("https://www.infoblox.com/blog/threat-intelligence/"
                "cloudy-with-a-chance-of-hijacking-forgotten-dns-records-enable-scam-actor/"),
        "verified_via": "research brief [3]",
    },
    "watchtowr-s3-2025": {
        "title": "watchTowr 2025: ~150 abandoned S3 bucket names re-registered by another account",
        "url": "https://labs.watchtowr.com/8-million-requests-later-we-made-the-solarwinds-supply-chain-attack-look-amateur/",
        "verified_via": "research brief [6]; demonstrates global-namespace names are reusable after deletion",
    },
    "cito-fingerprints": {
        "title": "EdOverflow/can-i-take-over-xyz fingerprints.json (CC BY 4.0)",
        "url": "https://github.com/EdOverflow/can-i-take-over-xyz",
        "verified_via": "vendored at commit 5bd4e12837911c8475486f1da922c9b9c706e632 (2025-02-08), "
                        "sha256 a108bf6e6d10d4e4861c4293eef8c224a0fd243ec4f3a39de321de69f284c64f",
    },
    "w3c-sri": {
        "title": "W3C Subresource Integrity",
        "url": "https://www.w3.org/TR/SRI/",
        "verified_via": "standard; browsers refuse a script/stylesheet whose hash does not match",
    },
}
