"""Source register for every rule the engine applies.

Each rule in ``providers.py`` cites one or more of these ids. "verified_via"
records how the fact was cross-checked when the knowledge base was built
(2026-10-01).
"""

SOURCES = {
    "aws-sdk-s3-createbucket": {
        "title": "AWS SDK service model, S3 CreateBucket / BucketNamespace (botocore s3 2006-03-01 service-2.json)",
        "quote": ("General purpose buckets exist in a global namespace, which means that each bucket name must "
                  "be unique across all Amazon Web Services accounts in all the Amazon Web Services Regions "
                  "within a partition."),
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "aws-sdk-s3-account-regional": {
        "title": "AWS SDK service model, S3 CreateBucket BucketNamespace member (x-amz-bucket-namespace)",
        "quote": ("Your account regional namespace is a subdivision of the global namespace that only your account "
                  "can create buckets in. ... Bucket names must follow the format "
                  "bucket-name-prefix-accountId-region-an (for example, amzn-s3-demo-bucket-111122223333-us-west-2-an)."),
        "verified_via": "botocore data model shipped with boto3 1.43.106; enum values account-regional | global",
    },
    "aws-sdk-s3-expected-owner": {
        "title": "AWS SDK service model, ExpectedBucketOwner (x-amz-expected-bucket-owner)",
        "quote": ("If the account ID that you provide does not match the actual owner of the bucket, the request "
                  "fails with the HTTP status code 403 Forbidden (access denied)."),
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "tf-aws-provider-schema": {
        "title": "Terraform AWS provider 6.67.0 schema: aws_s3_bucket.bucket_namespace, website_endpoint",
        "quote": "aws_s3_bucket attributes include bucket, bucket_prefix, bucket_namespace, website_endpoint",
        "verified_via": "terraform providers schema -json (Terraform 1.16.4, provider SHA256 verified)",
    },
    "aws-sdk-eb-checkdns": {
        "title": "AWS SDK service model, Elastic Beanstalk CheckDNSAvailability",
        "quote": "Checks if the specified CNAME is available. / CNAMEPrefix: The prefix used when this CNAME is reserved.",
        "verified_via": "botocore data model shipped with boto3 1.43.106",
    },
    "azure-sdk-web-label-scope": {
        "title": "Azure SDK azure-mgmt-web 11.0.1, autoGeneratedDomainNameLabelScope (not exposed by azurerm 5.7.0 "
                 "web app resources; reaches RetireSafe only from ARM exports)",
        "quote": ("Indicates the endpoint name reuse scope. The default value is TenantReuse. Supported values are "
                  "TenantReuse, SubscriptionReuse, ResourceGroupReuse, NoReuse."),
        "verified_via": "azure-mgmt-web 11.0.1 model docstrings",
    },
    "ms-learn-dangling-dns": {
        "title": "Microsoft Learn: Prevent dangling DNS entries and avoid subdomain takeover",
        "url": "https://learn.microsoft.com/en-us/azure/security/fundamentals/subdomain-takeover",
        "quote": ("Resource table: Azure Front Door (azurefd.net), Blob Storage (blob.core.windows.net), CDN "
                  "(azureedge.net), Public IP addresses (cloudapp.azure.com), Traffic Manager (trafficmanager.net), "
                  "Container Instance (azurecontainer.io), API Management (azure-api.net), App Service and slots "
                  "(azurewebsites.net)."),
        "verified_via": "article source MicrosoftDocs/azure-docs articles/security/fundamentals/"
                        "subdomain-takeover.md at commit 7f7c8f656864",
    },
    "azure-sdk-aci-reuse-policy": {
        "title": "Azure SDK azure-mgmt-containerinstance 10.1.0, DnsNameLabelReusePolicy",
        "quote": ("The 'Unsecure' value is the default value if not selected and means the object's domain name "
                  "label is not secured against subdomain takeover. ... The 'NoReuse' value means the object's "
                  "domain name label cannot be reused within the same resource group, subscription, or tenant."),
        "verified_via": "azure-mgmt-containerinstance 10.1.0 wheel; azurerm 5.7.0 attribute dns_name_label_reuse_policy",
    },
    "azure-sdk-publicip-label-scope": {
        "title": "Azure SDK azure-mgmt-network 33.0.0, PublicIpAddressDnsSettingsDomainNameLabelScope",
        "quote": ("If a domain name label and a domain name label scope are specified, an A DNS record is created "
                  "for the public IP in the Microsoft Azure DNS system with a hashed value includes in FQDN."),
        "verified_via": "azure-mgmt-network 33.0.0 wheel; azurerm 5.7.0 attribute domain_name_label_scope",
    },
    "assetnote-ghostbuster": {
        "title": "Assetnote 2022: Eliminating Dangling Elastic IP Takeovers with Ghostbuster",
        "url": "https://www.assetnote.io/resources/research/eliminating-dangling-elastic-ip-takeovers-with-ghostbuster",
        "quote": "Attackers can continually claim elastic IPs until they obtain an IP associated with a subdomain "
                 "of a targeted company.",
        "verified_via": "research write-up and open-source tool (github.com/assetnote/ghostbuster)",
    },
    "infoblox-cdc-2025": {
        "title": "Infoblox 2025: CDC abandoned Azure endpoint takeover",
        "url": "https://www.infoblox.com/blog/threat-intelligence/how-scammers-hijack-major-brands/",
        "verified_via": "research brief [2]",
    },
    "infoblox-hazyhawk-2025": {
        "title": "Infoblox 2025: Hazy Hawk (incl. hijacked oercommons S3 bucket)",
        "url": ("https://www.infoblox.com/blog/threat-intelligence/"
                "cloudy-with-a-chance-of-hijacking-forgotten-dns-records-enable-scam-actor/"),
        "verified_via": "research brief [3]",
    },
    "watchtowr-s3-2025": {
        "title": "watchTowr 2025: ~150 abandoned S3 bucket names re-registered by another account",
        "url": "https://labs.watchtowr.com/8-million-requests-later-we-made-the-solarwinds-supply-chain-attack-look-amateur/",
        "verified_via": "research brief [6]; demonstrates global-namespace names are reusable after deletion",
    },
    "cito-fingerprints": {
        "title": "EdOverflow/can-i-take-over-xyz fingerprints.json (CC BY 4.0)",
        "url": "https://github.com/EdOverflow/can-i-take-over-xyz",
        "verified_via": "vendored at commit 5bd4e12837911c8475486f1da922c9b9c706e632 (2025-02-08), "
                        "sha256 a108bf6e6d10d4e4861c4293eef8c224a0fd243ec4f3a39de321de69f284c64f",
    },
    "aws-s3-bucket-quota-2024": {
        "title": "AWS What's New, 14 Nov 2024: Amazon S3 now supports up to 1 million buckets per AWS account",
        "url": "https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-up-1-million-buckets-per-aws-account/",
        "quote": "default bucket quota of 10,000 ... not billed for the first 2,000 general purpose buckets",
        "verified_via": "AWS announcement (via search results; aws.amazon.com blocked in the build sandbox)",
    },
    "aws-ipv4-charge-2024": {
        "title": "AWS: public IPv4 address charge from 1 February 2024",
        "url": "https://aws.amazon.com/blogs/networking-and-content-delivery/identify-and-optimize-public-ipv4-address-usage-on-aws/",
        "quote": "$0.005 per IP per hour for all public IPv4 addresses, whether attached to a service or not",
        "verified_via": "AWS networking blog and re:Post articles (via search results)",
    },
    "w3c-sri": {
        "title": "W3C Subresource Integrity",
        "url": "https://www.w3.org/TR/SRI/",
        "verified_via": "standard; browsers refuse a script/stylesheet whose hash does not match",
    },
}
